enyo.depends(
	"source/Saved4Later.js",
	"source/MainView.js",
	"source/Preferences.js",
	"source/LoginDialog.js",
	"css/Saved4Later.css",
	"source/StoryList.js",
	"source/StoryView.js",
	//"source/database-enyo.js",
	"source/Database.js"
);
